# .github/workflows/docker-springboot.yml
name: Spring Boot CI/CD

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Build Java app
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn clean install

      # 3. Check build artifacts
      - name: Show built jar
        run: ls -l target/

      # 4. Docker login
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 5. QEMU setup (optional for multi-arch)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # 6. Buildx setup
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 7. Build and push Docker image
      - name: Build & push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .                    # root of your repo
          file: Dockerfile             # or specify if in target/
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/my-app:latest
