name: Spring Boot CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install

      - name: Debug
        run: ls -l target/
          - uses: mr-smithers-excellent/docker-build-push@v6
          name: Build & push Docker image
          with:
            image: repo/image
            tags: v1, latest
            registry: registry-url.io
            dockerfile: Dockerfile.ci
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}